# Generated by Django 4.2.5 on 2024-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id usuario')),
                ('imagen', models.CharField(max_length=50, unique=True, verbose_name='Ruta de imagen')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Correo Electrónico')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('es_admin', models.BooleanField(default=False, verbose_name='Es administrador')),
                ('contrasena', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
    ]
