# Generated by Django 4.2.5 on 2024-04-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.CharField(default='', max_length=50, verbose_name='Ruta de imagen'),
        ),
    ]
